### PR TITLE
Fix issues when using nvme drives

### PR DESCRIPTION
**Pull request by cdchris12**
This PR resolves the issues I ran into when using this tool to flash HiveOS onto rigs when using nvme storage by adding a 5 second wait after calling `partprobe` in order to give the OS time to actually update its mount points before trying to mount said mount points. I've also added some logic fixes to better handle the detection and usage of nvme drives, along with a couple more text prompts.

### CODE REVIEW

**Comment by ashkrig6003** [comment]
cdchris12:master

**Comment by cdchris12** [comment]
@dimafern @biospb It's been over 5 months since I put this PR in... Any chance y'all can review and/or merge this PR?

**Comment by cdchris12** [comment]
@dimafern @biospb Bueller?

**Comment by biospb** [comment]
one of the commits has bug so it never removes partition from nvme drive name.
the only useful thing seems to be delay after partprobe.

**Comment by cdchris12** [comment]
@biospb Can you be more specific with what bug this PR has? 

I can tell you that this PR has worked perfectly for me across a multitude of motherboards that I was able to test with

**Comment by tswizzle2** [comment]
> @biospb Can you be more specific with what bug this PR has?
> 
> I can tell you that this PR has worked perfectly for me across a multitude of motherboards that I was able to test with

Hi, can you compile your fix? I tried their version recently and it still fails with the same error

**Pull request closed without merging**
